apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: db
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.db.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
