apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: db
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.secret.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.db.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.secret.postgresPassword | quote }}
