apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    app: 3tier
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    app: 3tier
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    app: 3tier
