apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: db
automountServiceAccountToken: false
